// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnJPZp1a4JWpM3JdRcZMdi5giwGvPlGhg',
    appId: '1:826231281911:web:488636751579086def5bf2',
    messagingSenderId: '826231281911',
    projectId: 'petlife-12b5d',
    authDomain: 'petlife-12b5d.firebaseapp.com',
    storageBucket: 'petlife-12b5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIJfSXCXlLSikkvfzkIXl5_RbqvC6KnVI',
    appId: '1:826231281911:android:ae427455de42724def5bf2',
    messagingSenderId: '826231281911',
    projectId: 'petlife-12b5d',
    storageBucket: 'petlife-12b5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbuDQylCo7-8eKNM732ffWH9ih3JVC61s',
    appId: '1:826231281911:ios:677c8193fe9208aeef5bf2',
    messagingSenderId: '826231281911',
    projectId: 'petlife-12b5d',
    storageBucket: 'petlife-12b5d.appspot.com',
    iosBundleId: 'br.ufsm.csi.pdm.petshopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbuDQylCo7-8eKNM732ffWH9ih3JVC61s',
    appId: '1:826231281911:ios:677c8193fe9208aeef5bf2',
    messagingSenderId: '826231281911',
    projectId: 'petlife-12b5d',
    storageBucket: 'petlife-12b5d.appspot.com',
    iosBundleId: 'br.ufsm.csi.pdm.petshopapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnJPZp1a4JWpM3JdRcZMdi5giwGvPlGhg',
    appId: '1:826231281911:web:5eec6f14415900ffef5bf2',
    messagingSenderId: '826231281911',
    projectId: 'petlife-12b5d',
    authDomain: 'petlife-12b5d.firebaseapp.com',
    storageBucket: 'petlife-12b5d.appspot.com',
  );

}